# Generated by Django 3.2.5 on 2021-07-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDB',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('disease', models.TextField(max_length=1000)),
                ('doctorName', models.CharField(max_length=50)),
                ('doctorFees', models.IntegerField(default=500, max_length=5)),
                ('startMedsDate', models.CharField(max_length=15)),
            ],
        ),
    ]
